trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get install -y openjdk-7-jdk
    export JAVA_HOME_7_X64=/usr/lib/jvm/java-7-openjdk-amd64
    export PATH=$JAVA_HOME_7_X64/bin:$PATH
    java -version
  displayName: 'Install and use JDK 1.7'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.7'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'
