trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  JAVA_HOME: '/usr/lib/jvm/java-17-openjdk-amd64'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
    echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME)/bin:$(PATH)"
    java -version
  displayName: 'Install and use JDK 17'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    goals: 'clean install'
